/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
  AiOutlinePhone 
} from 'react-icons/ai';
import { MdAlternateEmail } from 'react-icons/md';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import computer from '../public/desktop.png'
import coffee from '../public/coffee.png';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Its NK Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-700 px-10 md:px-20 lg:px-60'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons text-teal-700'>NK Dev</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'
                >
                  Resume
                  </a>
              </li>
            </ul>
          </nav>
          
          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-6xl'>
              Neil-Jordan Kitson
              </h2>
            <h3 className='text-2xl py-2 text-white md: text-3xl' >Developer & designer</h3>
            <p className='text-md py-5 leading-8 text-white md: text-xl max-w-xl mx-auto'>
              Young developer providing services for programming and content design needs.
              Send me an email and let's get to work!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-12 py-3 text-gray-100'>
            <a href='http://twitter.com' className='onHover'>
              <AiFillTwitterCircle />
            </a>
            
            <a href='https://www.linkedin.com/in/neil-jordan-kitson-34890286/' className='hover:object-scale-down'>
              <AiFillLinkedin />
            </a>
            
            <a href='https://github.com/Neil-Jordan'>
              <AiFillGithub/>
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} className='fill' alt='appeal image'/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1 text-gray-200'>About Me</h3>
            <p className='text-md py-2 leading-8 text-gray-200'>
              I'm a self-taught developer with tons of enthusiasm, and a love of all things technology.  
              I've got experience working with <span className='text-teal-600'>HTML, CSS, JavaScript</span> and a fair bit of <span className='text-teal-600'>Object-oriented programming</span>.
            </p>
            <p className='text-md py-2 leading-8 text-gray-100'>
              With my know-how and your ideas, we can make dreams into reality
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg shadow-black p-10 rounded-lg my-10'>
              <div className='flex justify-center'>
                <Image src={design} alt='design image' width={175} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2 text-gray-200'>Great Designs</h3>
              <p className='py-2 text-white'>                
                Elegant designs tailored to your needs.
              </p>
              <h4 className='py-2 text-teal-700 text-2xl font-semibold'> Tools I use</h4>
              <p className='text-gray-100 py-1'>ReactJS</p>
              <p className='text-gray-100 py-1'>Visual Studio</p>   
              <p className='text-gray-100 py-1'>Object-Oriented</p>   
            </div>

            <div className='text-center shadow-lg shadow-black p-10 rounded-lg my-10'>
              <div className='flex justify-center md:w-10'>
                <Image src={computer} alt='design image' width={125} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2 text-gray-200'>Projects I'm Working On</h3>
              <p className='py-2 text-white'>                
                See what I'm involved in and what I've already done...
              </p>
              <div className='flex justify-evenly'>
                <a href='#' className='text-gray-100 py-1'>Calculator App</a>
                <a href='#' className='text-gray-100 py-1'>CSS Practice</a>   
                <a href='#' className='text-gray-100 py-1'>JavaScript</a>
              </div>   
            </div>
            
            <div className='text-center shadow-lg shadow-black p-5 rounded-lg my-10'>
              <div className='flex justify-center'>
                <Image src={coffee} alt='coffee image' width={175} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2 text-gray-200'>Contact Me</h3>
              <p className='py-2 text-white'>                
                Let's chat. Grab a coffee (or tea) with me.
              </p>
            
              <div className='text-gray-100 py-1 flex justify-center'>
                <AiOutlinePhone /> 
              </div>  
              <p  className='text-gray-100 py-1'>(416) 700-9044</p>
              
              <div className='text-gray-100 py-1 flex justify-center'>
                <MdAlternateEmail className='text-center' />
              </div>
              <p className='text-gray-100 py-1'>NKDoesDev@gmail.com</p>

            </div>

          </div>
        </section>
      </main>
    </div>
  );
}